int8 kAdjacentLeft = 0       # lane marking on the left side next to ego lane 
int8 kEgoLeft = 1            # left lane marking of the ego lane 
int8 kEgoRight = 2           # right lane marking of the ego lane 
int8 kAdjacentRight = 3      # lane marking on the right side next to ego lane 
int8 kThirdLeft = 4
int8 kThirdRight = 5 
int8 kFourthLeft = 6
int8 kFourthRight = 7 
int8 kOther = 8
int8 value