int8 kLineSingleSolid = 0   # 实线
int8 kLineSingleDashed = 1  # 虚线
int8 kLineBold = 2          # 短粗虚线（道路出入口标线）
int8 kLineDoubleSolid = 3   # 双实线
int8 kLineDoubleDashed = 4  # 双虚线
int8 kLineSolidDashed = 5   # 实虚线
int8 kLineDashedSolid = 6   # 虚实线
int8 kFence = 7             # 栅栏
int8 kCurb=8                # 路沿
int8 kLineFishboneSolid = 9  # 减速线-实线
int8 kLineFishboneDashed = 10  # 减速线-虚线
int8 kLineChangeable = 11      # 可变车道线
int8 kLineUnknown = 12
int8 value