# 目标检测分类
int8 kNone = 0
int8 kVehicle = 1                           # 车辆 
int8 kPed = 2                               # 行人
int8 kBike = 3                              # 二轮车
int8 kCone = 4                              # 锥桶
 
int8 kVehicleWheel = 5                      # 车轮
int8 kVehiclePlate = 6                      # 车牌
int8 kPedHead = 7                           # 人头
 
int8 kSmallTrafficSign = 10                 # 小标牌
int8 kBigTrafficSign = 11                   # 大标牌
int8 kTrafficLight = 12                     # 交通信号灯
int8 kAnimals = 13                          # 动物
int8 kVehicleLight = 14                     # 车灯
int8 kStreetLamp = 15                       # 路灯
int8 kObjectTypeNum = 16

int8 value