// Generated by gencpp from file mviz_apa_show/ColorType.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_COLORTYPE_H
#define MVIZ_APA_SHOW_MESSAGE_COLORTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/ColorTypeEnum.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct ColorType_
{
  typedef ColorType_<ContainerAllocator> Type;

  ColorType_()
    : type()  {
    }
  ColorType_(const ContainerAllocator& _alloc)
    : type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator>  _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::mviz_apa_show::ColorType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::ColorType_<ContainerAllocator> const> ConstPtr;

}; // struct ColorType_

typedef ::mviz_apa_show::ColorType_<std::allocator<void> > ColorType;

typedef boost::shared_ptr< ::mviz_apa_show::ColorType > ColorTypePtr;
typedef boost::shared_ptr< ::mviz_apa_show::ColorType const> ColorTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::ColorType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::ColorType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::ColorType_<ContainerAllocator1> & lhs, const ::mviz_apa_show::ColorType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::ColorType_<ContainerAllocator1> & lhs, const ::mviz_apa_show::ColorType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::ColorType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::ColorType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::ColorType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::ColorType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::ColorType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::ColorType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::ColorType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5949a3af45d239e9a8aea2bd9b037466";
  }

  static const char* value(const ::mviz_apa_show::ColorType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5949a3af45d239e9ULL;
  static const uint64_t static_value2 = 0xa8aea2bd9b037466ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::ColorType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/ColorType";
  }

  static const char* value(const ::mviz_apa_show::ColorType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::ColorType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ColorTypeEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/ColorTypeEnum\n"
"int8 kColorWhite = 0    # 白色\n"
"int8 kColorYellow = 1   # 黄色\n"
"int8 kColorOrange = 2   # 橙色\n"
"int8 kColorBlue = 3     # 蓝色\n"
"int8 kColorGreen = 4    # 绿色\n"
"int8 kColorGray = 5     # 灰色\n"
"int8 kColorWhiteYellow = 6  # 左白右黄\n"
"int8 kColorYellowWhite = 7  # 左黄右白\\\n"
"int8 kColorYellowGrayFusion = 8  # 黄灰混合\n"
"int8 kColorUnknown = 9  # \n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::ColorType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::ColorType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::ColorType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::ColorType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_COLORTYPE_H
