// Generated by gencpp from file mviz_apa_show/ColorTypeEnum.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_COLORTYPEENUM_H
#define MVIZ_APA_SHOW_MESSAGE_COLORTYPEENUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mviz_apa_show
{
template <class ContainerAllocator>
struct ColorTypeEnum_
{
  typedef ColorTypeEnum_<ContainerAllocator> Type;

  ColorTypeEnum_()
    : value(0)  {
    }
  ColorTypeEnum_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kColorWhite)
  #undef kColorWhite
#endif
#if defined(_WIN32) && defined(kColorYellow)
  #undef kColorYellow
#endif
#if defined(_WIN32) && defined(kColorOrange)
  #undef kColorOrange
#endif
#if defined(_WIN32) && defined(kColorBlue)
  #undef kColorBlue
#endif
#if defined(_WIN32) && defined(kColorGreen)
  #undef kColorGreen
#endif
#if defined(_WIN32) && defined(kColorGray)
  #undef kColorGray
#endif
#if defined(_WIN32) && defined(kColorWhiteYellow)
  #undef kColorWhiteYellow
#endif
#if defined(_WIN32) && defined(kColorYellowWhite)
  #undef kColorYellowWhite
#endif
#if defined(_WIN32) && defined(kColorYellowGrayFusion)
  #undef kColorYellowGrayFusion
#endif
#if defined(_WIN32) && defined(kColorUnknown)
  #undef kColorUnknown
#endif

  enum {
    kColorWhite = 0,
    kColorYellow = 1,
    kColorOrange = 2,
    kColorBlue = 3,
    kColorGreen = 4,
    kColorGray = 5,
    kColorWhiteYellow = 6,
    kColorYellowWhite = 7,
    kColorYellowGrayFusion = 8,
    kColorUnknown = 9,
  };


  typedef boost::shared_ptr< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> const> ConstPtr;

}; // struct ColorTypeEnum_

typedef ::mviz_apa_show::ColorTypeEnum_<std::allocator<void> > ColorTypeEnum;

typedef boost::shared_ptr< ::mviz_apa_show::ColorTypeEnum > ColorTypeEnumPtr;
typedef boost::shared_ptr< ::mviz_apa_show::ColorTypeEnum const> ColorTypeEnumConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe76c0fae59bcbf3975a80ef54187921";
  }

  static const char* value(const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe76c0fae59bcbf3ULL;
  static const uint64_t static_value2 = 0x975a80ef54187921ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/ColorTypeEnum";
  }

  static const char* value(const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 kColorWhite = 0    # 白色\n"
"int8 kColorYellow = 1   # 黄色\n"
"int8 kColorOrange = 2   # 橙色\n"
"int8 kColorBlue = 3     # 蓝色\n"
"int8 kColorGreen = 4    # 绿色\n"
"int8 kColorGray = 5     # 灰色\n"
"int8 kColorWhiteYellow = 6  # 左白右黄\n"
"int8 kColorYellowWhite = 7  # 左黄右白\\\n"
"int8 kColorYellowGrayFusion = 8  # 黄灰混合\n"
"int8 kColorUnknown = 9  # \n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorTypeEnum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::ColorTypeEnum_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_COLORTYPEENUM_H
