// Generated by gencpp from file mviz_apa_show/DataSource.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_DATASOURCE_H
#define MVIZ_APA_SHOW_MESSAGE_DATASOURCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/DataSourceEnum.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct DataSource_
{
  typedef DataSource_<ContainerAllocator> Type;

  DataSource_()
    : source()  {
    }
  DataSource_(const ContainerAllocator& _alloc)
    : source(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mviz_apa_show::DataSourceEnum_<ContainerAllocator>  _source_type;
  _source_type source;





  typedef boost::shared_ptr< ::mviz_apa_show::DataSource_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::DataSource_<ContainerAllocator> const> ConstPtr;

}; // struct DataSource_

typedef ::mviz_apa_show::DataSource_<std::allocator<void> > DataSource;

typedef boost::shared_ptr< ::mviz_apa_show::DataSource > DataSourcePtr;
typedef boost::shared_ptr< ::mviz_apa_show::DataSource const> DataSourceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::DataSource_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::DataSource_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::DataSource_<ContainerAllocator1> & lhs, const ::mviz_apa_show::DataSource_<ContainerAllocator2> & rhs)
{
  return lhs.source == rhs.source;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::DataSource_<ContainerAllocator1> & lhs, const ::mviz_apa_show::DataSource_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::DataSource_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::DataSource_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::DataSource_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::DataSource_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::DataSource_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::DataSource_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::DataSource_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e7b2eeffad386de4215a57c0468fe5d";
  }

  static const char* value(const ::mviz_apa_show::DataSource_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e7b2eeffad386deULL;
  static const uint64_t static_value2 = 0x4215a57c0468fe5dULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::DataSource_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/DataSource";
  }

  static const char* value(const ::mviz_apa_show::DataSource_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::DataSource_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DataSourceEnum source\n"
"================================================================================\n"
"MSG: mviz_apa_show/DataSourceEnum\n"
"int8 kMinieye   = 0\n"
"int8 kEyeQ3     = 1\n"
"int8 kEyeQ4     = 2\n"
"int8 kJ2        = 3\n"
"int8 kLidar     = 4      # 纯激光雷达\n"
"int8 kCamera    = 5      # 纯摄像头\n"
"int8 kCameraLidar = 6    # 摄像头激光雷达融合\n"
"int8 kUltraRadar = 7     # 超声波雷达\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::DataSource_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::DataSource_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataSource_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::DataSource_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::DataSource_<ContainerAllocator>& v)
  {
    s << indent << "source: ";
    s << std::endl;
    Printer< ::mviz_apa_show::DataSourceEnum_<ContainerAllocator> >::stream(s, indent + "  ", v.source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_DATASOURCE_H
