// Generated by gencpp from file mviz_apa_show/FreespaceObstacle.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_FREESPACEOBSTACLE_H
#define MVIZ_APA_SHOW_MESSAGE_FREESPACEOBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/Point2f.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct FreespaceObstacle_
{
  typedef FreespaceObstacle_<ContainerAllocator> Type;

  FreespaceObstacle_()
    : id(0)
    , points()  {
    }
  FreespaceObstacle_(const ContainerAllocator& _alloc)
    : id(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::vector< ::mviz_apa_show::Point2f_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mviz_apa_show::Point2f_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> const> ConstPtr;

}; // struct FreespaceObstacle_

typedef ::mviz_apa_show::FreespaceObstacle_<std::allocator<void> > FreespaceObstacle;

typedef boost::shared_ptr< ::mviz_apa_show::FreespaceObstacle > FreespaceObstaclePtr;
typedef boost::shared_ptr< ::mviz_apa_show::FreespaceObstacle const> FreespaceObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator1> & lhs, const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator1> & lhs, const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb9d47b7f53c4f0f3fa86b4e87d2b516";
  }

  static const char* value(const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb9d47b7f53c4f0fULL;
  static const uint64_t static_value2 = 0x3fa86b4e87d2b516ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/FreespaceObstacle";
  }

  static const char* value(const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"Point2f[] points\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point2f\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreespaceObstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::FreespaceObstacle_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mviz_apa_show::Point2f_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_FREESPACEOBSTACLE_H
