// Generated by gencpp from file mviz_apa_show/LanelinePositionType.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_LANELINEPOSITIONTYPE_H
#define MVIZ_APA_SHOW_MESSAGE_LANELINEPOSITIONTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/LanelinePositionTypeEnum.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct LanelinePositionType_
{
  typedef LanelinePositionType_<ContainerAllocator> Type;

  LanelinePositionType_()
    : type()  {
    }
  LanelinePositionType_(const ContainerAllocator& _alloc)
    : type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mviz_apa_show::LanelinePositionTypeEnum_<ContainerAllocator>  _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> const> ConstPtr;

}; // struct LanelinePositionType_

typedef ::mviz_apa_show::LanelinePositionType_<std::allocator<void> > LanelinePositionType;

typedef boost::shared_ptr< ::mviz_apa_show::LanelinePositionType > LanelinePositionTypePtr;
typedef boost::shared_ptr< ::mviz_apa_show::LanelinePositionType const> LanelinePositionTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator1> & lhs, const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator1> & lhs, const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10fd38bdec79ca5f3209f67e44c2aed3";
  }

  static const char* value(const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10fd38bdec79ca5fULL;
  static const uint64_t static_value2 = 0x3209f67e44c2aed3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/LanelinePositionType";
  }

  static const char* value(const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LanelinePositionTypeEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/LanelinePositionTypeEnum\n"
"int8 kAdjacentLeft = 0       # lane marking on the left side next to ego lane \n"
"int8 kEgoLeft = 1            # left lane marking of the ego lane \n"
"int8 kEgoRight = 2           # right lane marking of the ego lane \n"
"int8 kAdjacentRight = 3      # lane marking on the right side next to ego lane \n"
"int8 kThirdLeft = 4\n"
"int8 kThirdRight = 5 \n"
"int8 kFourthLeft = 6\n"
"int8 kFourthRight = 7 \n"
"int8 kOther = 8\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanelinePositionType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::LanelinePositionType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::LanelinePositionTypeEnum_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_LANELINEPOSITIONTYPE_H
