// Generated by gencpp from file mviz_apa_show/Laneline.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_LANELINE_H
#define MVIZ_APA_SHOW_MESSAGE_LANELINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/LineType.h>
#include <mviz_apa_show/LanelinePositionType.h>
#include <mviz_apa_show/ColorType.h>
#include <mviz_apa_show/CurveCoeff.h>
#include <mviz_apa_show/CurveCoeff.h>
#include <mviz_apa_show/Point2fList.h>
#include <mviz_apa_show/Point3DList.h>
#include <mviz_apa_show/Point2fList.h>
#include <mviz_apa_show/Point3DList.h>
#include <mviz_apa_show/LineState.h>
#include <mviz_apa_show/Point2f.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct Laneline_
{
  typedef Laneline_<ContainerAllocator> Type;

  Laneline_()
    : type()
    , pos_type()
    , color_type()
    , curve_vehicle_coord()
    , curve_image_coord()
    , points_image_coord()
    , points_vehicle_coord()
    , fit_points_image_coord()
    , fit_points_vehicle_coord()
    , id(0)
    , line_state()
    , confidence(0.0)
    , width(0.0)
    , age(0)
    , point_cam_id()
    , centroid_pt()
    , lane_id(0)  {
    }
  Laneline_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , pos_type(_alloc)
    , color_type(_alloc)
    , curve_vehicle_coord(_alloc)
    , curve_image_coord(_alloc)
    , points_image_coord(_alloc)
    , points_vehicle_coord(_alloc)
    , fit_points_image_coord(_alloc)
    , fit_points_vehicle_coord(_alloc)
    , id(0)
    , line_state(_alloc)
    , confidence(0.0)
    , width(0.0)
    , age(0)
    , point_cam_id(_alloc)
    , centroid_pt(_alloc)
    , lane_id(0)  {
  (void)_alloc;
    }



   typedef  ::mviz_apa_show::LineType_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef  ::mviz_apa_show::LanelinePositionType_<ContainerAllocator>  _pos_type_type;
  _pos_type_type pos_type;

   typedef  ::mviz_apa_show::ColorType_<ContainerAllocator>  _color_type_type;
  _color_type_type color_type;

   typedef  ::mviz_apa_show::CurveCoeff_<ContainerAllocator>  _curve_vehicle_coord_type;
  _curve_vehicle_coord_type curve_vehicle_coord;

   typedef  ::mviz_apa_show::CurveCoeff_<ContainerAllocator>  _curve_image_coord_type;
  _curve_image_coord_type curve_image_coord;

   typedef  ::mviz_apa_show::Point2fList_<ContainerAllocator>  _points_image_coord_type;
  _points_image_coord_type points_image_coord;

   typedef  ::mviz_apa_show::Point3DList_<ContainerAllocator>  _points_vehicle_coord_type;
  _points_vehicle_coord_type points_vehicle_coord;

   typedef  ::mviz_apa_show::Point2fList_<ContainerAllocator>  _fit_points_image_coord_type;
  _fit_points_image_coord_type fit_points_image_coord;

   typedef  ::mviz_apa_show::Point3DList_<ContainerAllocator>  _fit_points_vehicle_coord_type;
  _fit_points_vehicle_coord_type fit_points_vehicle_coord;

   typedef uint64_t _id_type;
  _id_type id;

   typedef  ::mviz_apa_show::LineState_<ContainerAllocator>  _line_state_type;
  _line_state_type line_state;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _width_type;
  _width_type width;

   typedef uint32_t _age_type;
  _age_type age;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _point_cam_id_type;
  _point_cam_id_type point_cam_id;

   typedef  ::mviz_apa_show::Point2f_<ContainerAllocator>  _centroid_pt_type;
  _centroid_pt_type centroid_pt;

   typedef int32_t _lane_id_type;
  _lane_id_type lane_id;





  typedef boost::shared_ptr< ::mviz_apa_show::Laneline_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::Laneline_<ContainerAllocator> const> ConstPtr;

}; // struct Laneline_

typedef ::mviz_apa_show::Laneline_<std::allocator<void> > Laneline;

typedef boost::shared_ptr< ::mviz_apa_show::Laneline > LanelinePtr;
typedef boost::shared_ptr< ::mviz_apa_show::Laneline const> LanelineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::Laneline_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::Laneline_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::Laneline_<ContainerAllocator1> & lhs, const ::mviz_apa_show::Laneline_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.pos_type == rhs.pos_type &&
    lhs.color_type == rhs.color_type &&
    lhs.curve_vehicle_coord == rhs.curve_vehicle_coord &&
    lhs.curve_image_coord == rhs.curve_image_coord &&
    lhs.points_image_coord == rhs.points_image_coord &&
    lhs.points_vehicle_coord == rhs.points_vehicle_coord &&
    lhs.fit_points_image_coord == rhs.fit_points_image_coord &&
    lhs.fit_points_vehicle_coord == rhs.fit_points_vehicle_coord &&
    lhs.id == rhs.id &&
    lhs.line_state == rhs.line_state &&
    lhs.confidence == rhs.confidence &&
    lhs.width == rhs.width &&
    lhs.age == rhs.age &&
    lhs.point_cam_id == rhs.point_cam_id &&
    lhs.centroid_pt == rhs.centroid_pt &&
    lhs.lane_id == rhs.lane_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::Laneline_<ContainerAllocator1> & lhs, const ::mviz_apa_show::Laneline_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::Laneline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::Laneline_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::Laneline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::Laneline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::Laneline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::Laneline_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::Laneline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be80bb4d13030e94b0cd8d40595600ee";
  }

  static const char* value(const ::mviz_apa_show::Laneline_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe80bb4d13030e94ULL;
  static const uint64_t static_value2 = 0xb0cd8d40595600eeULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::Laneline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/Laneline";
  }

  static const char* value(const ::mviz_apa_show::Laneline_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::Laneline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LineType type                                                # 线型 类型:int 字节数:4 取值范围:(0~8)\n"
"LanelinePositionType pos_type                                # 位置 类型:int 字节数:4 取值范围:(0~8)\n"
"ColorType color_type                                         # 颜色 类型:int 字节数:4 取值范围:(0~4)\n"
"CurveCoeff curve_vehicle_coord                               # 车身坐标系下曲线方程 字节数:40\n"
"CurveCoeff curve_image_coord                                 # 图像坐标下曲线方程   字节数:40\n"
"\n"
"Point2fList points_image_coord             # 图像坐标系下的点集 (检测)  字节数:16*n 取值范围(w>=x>=0, h>=y>=0) 最大容量:60\n"
"Point3DList points_vehicle_coord           # 车身坐标系下的点集 (检测) 字节数:24*n 取值范围(100>=x>=0, 20>=y>=-20) 最大容量:60\n"
"Point2fList fit_points_image_coord         # 图像坐标系下的点集 (拟合抽样) 字节数:16*n 取值范围(w>=x>=0, h>=y>=0) 最大容量:60\n"
"Point3DList fit_points_vehicle_coord       # 车身坐标系下的点集 (拟合抽样) 字节数:24*n 取值范围(100>=x>=0, 20>=y>=-20) 最大容量:60\n"
"uint64 id                                                   # id 类型:uint64 字节数:8 取值范围(0~2^64)\n"
"LineState line_state                                        # 线状态 类型:int 字节数:4 取值范围:(0~2)\n"
"float32 confidence                                            # 置信度 类型:float 字节数:4 取值范围:(0~1)\n"
"float32 width                                                 # 车道线宽度(单位:m) 类型:float 字节数:4 取值范围:(0, 0.6)\n"
"uint32 age                                                  # 声明周期 类型:uint32 字节数:4 取值范围:(0~2^32)\n"
"uint32[] point_cam_id                                # 采样点对应的camera id  字节数: 16*n 取值范围 最大容量:255   \n"
"Point2f centroid_pt                       # 质心点坐标\n"
"int32 lane_id                                               # 车道线位置id(当前车道左侧从0向远处递减，右侧从1向远处递增)\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineType\n"
"LineTypeEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineTypeEnum\n"
"int8 kLineSingleSolid = 0   # 实线\n"
"int8 kLineSingleDashed = 1  # 虚线\n"
"int8 kLineBold = 2          # 短粗虚线（道路出入口标线）\n"
"int8 kLineDoubleSolid = 3   # 双实线\n"
"int8 kLineDoubleDashed = 4  # 双虚线\n"
"int8 kLineSolidDashed = 5   # 实虚线\n"
"int8 kLineDashedSolid = 6   # 虚实线\n"
"int8 kFence = 7             # 栅栏\n"
"int8 kCurb=8                # 路沿\n"
"int8 kLineFishboneSolid = 9  # 减速线-实线\n"
"int8 kLineFishboneDashed = 10  # 减速线-虚线\n"
"int8 kLineChangeable = 11      # 可变车道线\n"
"int8 kLineUnknown = 12\n"
"int8 value\n"
"================================================================================\n"
"MSG: mviz_apa_show/LanelinePositionType\n"
"LanelinePositionTypeEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/LanelinePositionTypeEnum\n"
"int8 kAdjacentLeft = 0       # lane marking on the left side next to ego lane \n"
"int8 kEgoLeft = 1            # left lane marking of the ego lane \n"
"int8 kEgoRight = 2           # right lane marking of the ego lane \n"
"int8 kAdjacentRight = 3      # lane marking on the right side next to ego lane \n"
"int8 kThirdLeft = 4\n"
"int8 kThirdRight = 5 \n"
"int8 kFourthLeft = 6\n"
"int8 kFourthRight = 7 \n"
"int8 kOther = 8\n"
"int8 value\n"
"================================================================================\n"
"MSG: mviz_apa_show/ColorType\n"
"ColorTypeEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/ColorTypeEnum\n"
"int8 kColorWhite = 0    # 白色\n"
"int8 kColorYellow = 1   # 黄色\n"
"int8 kColorOrange = 2   # 橙色\n"
"int8 kColorBlue = 3     # 蓝色\n"
"int8 kColorGreen = 4    # 绿色\n"
"int8 kColorGray = 5     # 灰色\n"
"int8 kColorWhiteYellow = 6  # 左白右黄\n"
"int8 kColorYellowWhite = 7  # 左黄右白\\\n"
"int8 kColorYellowGrayFusion = 8  # 黄灰混合\n"
"int8 kColorUnknown = 9  # \n"
"int8 value\n"
"================================================================================\n"
"MSG: mviz_apa_show/CurveCoeff\n"
"# 曲线方程: y = c0 + c1*x + c2*x^2 + c3*x^3\n"
"float32 longitude_min  # view range start 类型:float 字节数:4 取值范围:(FLT_MIN~FLT_MAX)\n"
"float32 longitude_max  # view range end   类型:float 字节数:4 取值范围:(FLT_MIN~FLT_MAX)\n"
"float64 c0            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 c1            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 c2            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 c3            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 dev_c0        # c0的标准差，即，车道线横向位置的标准差\n"
"float64 dev_c1		  # c1的标准差，即，车道线航向角的标准差\n"
"float64 dev_c2        # c2的标准差，即，车道线原点处曲率的标准差\n"
"float64 dev_c3       # c3的标准差，即，车道线原点处曲率变化率的标注差\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point2fList\n"
"Point2f[] points\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point2f\n"
"float32 x\n"
"float32 y\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point3DList\n"
"geometry_msgs/Point[] points \n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineState\n"
"LineStateEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineStateEnum\n"
"int8 kDetected = 0      # 检测线\n"
"int8 kPredicted = 1     # 预测线\n"
"int8 kStableTrack = 2   # 稳定跟踪\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::Laneline_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::Laneline_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.pos_type);
      stream.next(m.color_type);
      stream.next(m.curve_vehicle_coord);
      stream.next(m.curve_image_coord);
      stream.next(m.points_image_coord);
      stream.next(m.points_vehicle_coord);
      stream.next(m.fit_points_image_coord);
      stream.next(m.fit_points_vehicle_coord);
      stream.next(m.id);
      stream.next(m.line_state);
      stream.next(m.confidence);
      stream.next(m.width);
      stream.next(m.age);
      stream.next(m.point_cam_id);
      stream.next(m.centroid_pt);
      stream.next(m.lane_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Laneline_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::Laneline_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::Laneline_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::LineType_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    s << indent << "pos_type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::LanelinePositionType_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_type);
    s << indent << "color_type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::ColorType_<ContainerAllocator> >::stream(s, indent + "  ", v.color_type);
    s << indent << "curve_vehicle_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::CurveCoeff_<ContainerAllocator> >::stream(s, indent + "  ", v.curve_vehicle_coord);
    s << indent << "curve_image_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::CurveCoeff_<ContainerAllocator> >::stream(s, indent + "  ", v.curve_image_coord);
    s << indent << "points_image_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point2fList_<ContainerAllocator> >::stream(s, indent + "  ", v.points_image_coord);
    s << indent << "points_vehicle_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point3DList_<ContainerAllocator> >::stream(s, indent + "  ", v.points_vehicle_coord);
    s << indent << "fit_points_image_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point2fList_<ContainerAllocator> >::stream(s, indent + "  ", v.fit_points_image_coord);
    s << indent << "fit_points_vehicle_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point3DList_<ContainerAllocator> >::stream(s, indent + "  ", v.fit_points_vehicle_coord);
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    s << indent << "line_state: ";
    s << std::endl;
    Printer< ::mviz_apa_show::LineState_<ContainerAllocator> >::stream(s, indent + "  ", v.line_state);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "age: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.age);
    s << indent << "point_cam_id[]" << std::endl;
    for (size_t i = 0; i < v.point_cam_id.size(); ++i)
    {
      s << indent << "  point_cam_id[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.point_cam_id[i]);
    }
    s << indent << "centroid_pt: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point2f_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid_pt);
    s << indent << "lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_LANELINE_H
