// Generated by gencpp from file mviz_apa_show/LineStateEnum.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_LINESTATEENUM_H
#define MVIZ_APA_SHOW_MESSAGE_LINESTATEENUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mviz_apa_show
{
template <class ContainerAllocator>
struct LineStateEnum_
{
  typedef LineStateEnum_<ContainerAllocator> Type;

  LineStateEnum_()
    : value(0)  {
    }
  LineStateEnum_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kDetected)
  #undef kDetected
#endif
#if defined(_WIN32) && defined(kPredicted)
  #undef kPredicted
#endif
#if defined(_WIN32) && defined(kStableTrack)
  #undef kStableTrack
#endif

  enum {
    kDetected = 0,
    kPredicted = 1,
    kStableTrack = 2,
  };


  typedef boost::shared_ptr< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> const> ConstPtr;

}; // struct LineStateEnum_

typedef ::mviz_apa_show::LineStateEnum_<std::allocator<void> > LineStateEnum;

typedef boost::shared_ptr< ::mviz_apa_show::LineStateEnum > LineStateEnumPtr;
typedef boost::shared_ptr< ::mviz_apa_show::LineStateEnum const> LineStateEnumConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::LineStateEnum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::LineStateEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::LineStateEnum_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::LineStateEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::LineStateEnum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "442d42c91d0bfc7e581435c471bcd8c7";
  }

  static const char* value(const ::mviz_apa_show::LineStateEnum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x442d42c91d0bfc7eULL;
  static const uint64_t static_value2 = 0x581435c471bcd8c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/LineStateEnum";
  }

  static const char* value(const ::mviz_apa_show::LineStateEnum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 kDetected = 0      # 检测线\n"
"int8 kPredicted = 1     # 预测线\n"
"int8 kStableTrack = 2   # 稳定跟踪\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::LineStateEnum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineStateEnum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::LineStateEnum_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_LINESTATEENUM_H
