// Generated by gencpp from file mviz_apa_show/LineState.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_LINESTATE_H
#define MVIZ_APA_SHOW_MESSAGE_LINESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/LineStateEnum.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct LineState_
{
  typedef LineState_<ContainerAllocator> Type;

  LineState_()
    : type()  {
    }
  LineState_(const ContainerAllocator& _alloc)
    : type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mviz_apa_show::LineStateEnum_<ContainerAllocator>  _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::mviz_apa_show::LineState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::LineState_<ContainerAllocator> const> ConstPtr;

}; // struct LineState_

typedef ::mviz_apa_show::LineState_<std::allocator<void> > LineState;

typedef boost::shared_ptr< ::mviz_apa_show::LineState > LineStatePtr;
typedef boost::shared_ptr< ::mviz_apa_show::LineState const> LineStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::LineState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::LineState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::LineState_<ContainerAllocator1> & lhs, const ::mviz_apa_show::LineState_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::LineState_<ContainerAllocator1> & lhs, const ::mviz_apa_show::LineState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::LineState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::LineState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::LineState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::LineState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::LineState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::LineState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::LineState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1124f51b88d479ab9b44dd08c088946";
  }

  static const char* value(const ::mviz_apa_show::LineState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1124f51b88d479aULL;
  static const uint64_t static_value2 = 0xb9b44dd08c088946ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::LineState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/LineState";
  }

  static const char* value(const ::mviz_apa_show::LineState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::LineState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LineStateEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineStateEnum\n"
"int8 kDetected = 0      # 检测线\n"
"int8 kPredicted = 1     # 预测线\n"
"int8 kStableTrack = 2   # 稳定跟踪\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::LineState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::LineState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::LineState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::LineState_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::LineStateEnum_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_LINESTATE_H
