// Generated by gencpp from file mviz_apa_show/MeasureTypeEnum.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_MEASURETYPEENUM_H
#define MVIZ_APA_SHOW_MESSAGE_MEASURETYPEENUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mviz_apa_show
{
template <class ContainerAllocator>
struct MeasureTypeEnum_
{
  typedef MeasureTypeEnum_<ContainerAllocator> Type;

  MeasureTypeEnum_()
    : value(0)  {
    }
  MeasureTypeEnum_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kVehicleMeasureHeadReg)
  #undef kVehicleMeasureHeadReg
#endif
#if defined(_WIN32) && defined(kVehicleMeasureTailReg)
  #undef kVehicleMeasureTailReg
#endif
#if defined(_WIN32) && defined(kVehicleMeasureDetect)
  #undef kVehicleMeasureDetect
#endif
#if defined(_WIN32) && defined(kVehicleMeasureWheel)
  #undef kVehicleMeasureWheel
#endif
#if defined(_WIN32) && defined(kVehicleMeasurePlate)
  #undef kVehicleMeasurePlate
#endif

  enum {
    kVehicleMeasureHeadReg = 0,
    kVehicleMeasureTailReg = 1,
    kVehicleMeasureDetect = 2,
    kVehicleMeasureWheel = 3,
    kVehicleMeasurePlate = 4,
  };


  typedef boost::shared_ptr< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> const> ConstPtr;

}; // struct MeasureTypeEnum_

typedef ::mviz_apa_show::MeasureTypeEnum_<std::allocator<void> > MeasureTypeEnum;

typedef boost::shared_ptr< ::mviz_apa_show::MeasureTypeEnum > MeasureTypeEnumPtr;
typedef boost::shared_ptr< ::mviz_apa_show::MeasureTypeEnum const> MeasureTypeEnumConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36239cfe88dbebd98b89b62788d5c45b";
  }

  static const char* value(const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36239cfe88dbebd9ULL;
  static const uint64_t static_value2 = 0x8b89b62788d5c45bULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/MeasureTypeEnum";
  }

  static const char* value(const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 kVehicleMeasureHeadReg = 0\n"
"int8 kVehicleMeasureTailReg = 1\n"
"int8 kVehicleMeasureDetect = 2\n"
"int8 kVehicleMeasureWheel = 3\n"
"int8 kVehicleMeasurePlate = 4\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MeasureTypeEnum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::MeasureTypeEnum_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_MEASURETYPEENUM_H
