// Generated by gencpp from file mviz_apa_show/ParkSlotTypeEnum.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_PARKSLOTTYPEENUM_H
#define MVIZ_APA_SHOW_MESSAGE_PARKSLOTTYPEENUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mviz_apa_show
{
template <class ContainerAllocator>
struct ParkSlotTypeEnum_
{
  typedef ParkSlotTypeEnum_<ContainerAllocator> Type;

  ParkSlotTypeEnum_()
    : value(0)  {
    }
  ParkSlotTypeEnum_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(kUnknown)
  #undef kUnknown
#endif
#if defined(_WIN32) && defined(kVerticalSpot)
  #undef kVerticalSpot
#endif
#if defined(_WIN32) && defined(kHorizontalSpot)
  #undef kHorizontalSpot
#endif
#if defined(_WIN32) && defined(kObliqueSpot)
  #undef kObliqueSpot
#endif

  enum {
    kUnknown = 0,
    kVerticalSpot = 1,
    kHorizontalSpot = 2,
    kObliqueSpot = 3,
  };


  typedef boost::shared_ptr< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> const> ConstPtr;

}; // struct ParkSlotTypeEnum_

typedef ::mviz_apa_show::ParkSlotTypeEnum_<std::allocator<void> > ParkSlotTypeEnum;

typedef boost::shared_ptr< ::mviz_apa_show::ParkSlotTypeEnum > ParkSlotTypeEnumPtr;
typedef boost::shared_ptr< ::mviz_apa_show::ParkSlotTypeEnum const> ParkSlotTypeEnumConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator1> & lhs, const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2ba5e48fd5f683e650f287cb42c2f56";
  }

  static const char* value(const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2ba5e48fd5f683eULL;
  static const uint64_t static_value2 = 0x650f287cb42c2f56ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/ParkSlotTypeEnum";
  }

  static const char* value(const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 kUnknown = 0 \n"
"int8 kVerticalSpot = 1           # 垂直车位\n"
"int8 kHorizontalSpot = 2         # 水平车位\n"
"int8 kObliqueSpot = 3            # 斜车位\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParkSlotTypeEnum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::ParkSlotTypeEnum_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_PARKSLOTTYPEENUM_H
