// Generated by gencpp from file mviz_apa_show/Planning.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_PLANNING_H
#define MVIZ_APA_SHOW_MESSAGE_PLANNING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/Trajectory.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct Planning_
{
  typedef Planning_<ContainerAllocator> Type;

  Planning_()
    : timestamp(0)
    , tick(0)
    , planning_status(0)
    , planning_trajectory()  {
    }
  Planning_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , tick(0)
    , planning_status(0)
    , planning_trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _tick_type;
  _tick_type tick;

   typedef uint32_t _planning_status_type;
  _planning_status_type planning_status;

   typedef  ::mviz_apa_show::Trajectory_<ContainerAllocator>  _planning_trajectory_type;
  _planning_trajectory_type planning_trajectory;





  typedef boost::shared_ptr< ::mviz_apa_show::Planning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::Planning_<ContainerAllocator> const> ConstPtr;

}; // struct Planning_

typedef ::mviz_apa_show::Planning_<std::allocator<void> > Planning;

typedef boost::shared_ptr< ::mviz_apa_show::Planning > PlanningPtr;
typedef boost::shared_ptr< ::mviz_apa_show::Planning const> PlanningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::Planning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::Planning_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::Planning_<ContainerAllocator1> & lhs, const ::mviz_apa_show::Planning_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.tick == rhs.tick &&
    lhs.planning_status == rhs.planning_status &&
    lhs.planning_trajectory == rhs.planning_trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::Planning_<ContainerAllocator1> & lhs, const ::mviz_apa_show::Planning_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::Planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::Planning_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::Planning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::Planning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::Planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::Planning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::Planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73f5db7d12063cc84657c071d1faeced";
  }

  static const char* value(const ::mviz_apa_show::Planning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73f5db7d12063cc8ULL;
  static const uint64_t static_value2 = 0x4657c071d1faecedULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::Planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/Planning";
  }

  static const char* value(const ::mviz_apa_show::Planning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::Planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp   # microseconds\n"
"uint64 tick\n"
"uint32 planning_status  #Planning Status, 0|defalt, 1|search spots, 2|waiting control, 3|has planing path, 4|replanning, 5|finish planing\n"
"Trajectory planning_trajectory\n"
"================================================================================\n"
"MSG: mviz_apa_show/Trajectory\n"
"uint64 timestamp\n"
"uint64 tick\n"
"uint32 id\n"
"int32 gear # 0-other, 1-R, 2-D\n"
"int32 type # 0-other, 1-line, 2-circle\n"
"TrajectoryPoint[] trajectory\n"
"float32 total_length\n"
"float32 total_time\n"
"================================================================================\n"
"MSG: mviz_apa_show/TrajectoryPoint\n"
"PathPoint path_point\n"
"float32 v\n"
"float32 a\n"
"float32 da\n"
"float32 rl_time\n"
"float32 steer\n"
"================================================================================\n"
"MSG: mviz_apa_show/PathPoint\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 theta\n"
"float32 s\n"
"float32 kappa\n"
"float32 dkappa\n"
"float32 ddkappa\n"
"float32 x_derivative\n"
"float32 y_derivative\n"
;
  }

  static const char* value(const ::mviz_apa_show::Planning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::Planning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.tick);
      stream.next(m.planning_status);
      stream.next(m.planning_trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Planning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::Planning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::Planning_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "tick: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.tick);
    s << indent << "planning_status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.planning_status);
    s << indent << "planning_trajectory: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Trajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.planning_trajectory);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_PLANNING_H
