// Generated by gencpp from file mviz_apa_show/PoseAngle.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_POSEANGLE_H
#define MVIZ_APA_SHOW_MESSAGE_POSEANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mviz_apa_show
{
template <class ContainerAllocator>
struct PoseAngle_
{
  typedef PoseAngle_<ContainerAllocator> Type;

  PoseAngle_()
    : pitch(0.0)
    , yaw(0.0)
    , roll(0.0)  {
    }
  PoseAngle_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , yaw(0.0)
    , roll(0.0)  {
  (void)_alloc;
    }



   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _roll_type;
  _roll_type roll;





  typedef boost::shared_ptr< ::mviz_apa_show::PoseAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::PoseAngle_<ContainerAllocator> const> ConstPtr;

}; // struct PoseAngle_

typedef ::mviz_apa_show::PoseAngle_<std::allocator<void> > PoseAngle;

typedef boost::shared_ptr< ::mviz_apa_show::PoseAngle > PoseAnglePtr;
typedef boost::shared_ptr< ::mviz_apa_show::PoseAngle const> PoseAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::PoseAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::PoseAngle_<ContainerAllocator1> & lhs, const ::mviz_apa_show::PoseAngle_<ContainerAllocator2> & rhs)
{
  return lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.roll == rhs.roll;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::PoseAngle_<ContainerAllocator1> & lhs, const ::mviz_apa_show::PoseAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::PoseAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::PoseAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::PoseAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7df065b9d568b6506284f9708f81ac8e";
  }

  static const char* value(const ::mviz_apa_show::PoseAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7df065b9d568b650ULL;
  static const uint64_t static_value2 = 0x6284f9708f81ac8eULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/PoseAngle";
  }

  static const char* value(const ::mviz_apa_show::PoseAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch\n"
"float32 yaw\n"
"float32 roll \n"
;
  }

  static const char* value(const ::mviz_apa_show::PoseAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::PoseAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::PoseAngle_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_POSEANGLE_H
