// Generated by gencpp from file mviz_apa_show/RoadmarkType.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_ROADMARKTYPE_H
#define MVIZ_APA_SHOW_MESSAGE_ROADMARKTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/RoadmarkTypeEnum.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct RoadmarkType_
{
  typedef RoadmarkType_<ContainerAllocator> Type;

  RoadmarkType_()
    : type()  {
    }
  RoadmarkType_(const ContainerAllocator& _alloc)
    : type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mviz_apa_show::RoadmarkTypeEnum_<ContainerAllocator>  _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> const> ConstPtr;

}; // struct RoadmarkType_

typedef ::mviz_apa_show::RoadmarkType_<std::allocator<void> > RoadmarkType;

typedef boost::shared_ptr< ::mviz_apa_show::RoadmarkType > RoadmarkTypePtr;
typedef boost::shared_ptr< ::mviz_apa_show::RoadmarkType const> RoadmarkTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::RoadmarkType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::RoadmarkType_<ContainerAllocator1> & lhs, const ::mviz_apa_show::RoadmarkType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::RoadmarkType_<ContainerAllocator1> & lhs, const ::mviz_apa_show::RoadmarkType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a804983a8b51f5cdae829b6211889547";
  }

  static const char* value(const ::mviz_apa_show::RoadmarkType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa804983a8b51f5cdULL;
  static const uint64_t static_value2 = 0xae829b6211889547ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/RoadmarkType";
  }

  static const char* value(const ::mviz_apa_show::RoadmarkType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoadmarkTypeEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/RoadmarkTypeEnum\n"
"int8 kBackGround = 0              # 背景\n"
"int8 kStraightArrow = 1           # 直行\n"
"int8 kLeftArrow = 2               # 左转\n"
"int8 kRightArrow = 3              # 右转\n"
"int8 kUturnArrow = 4              # 掉头\n"
"int8 kDiamond = 5                 # 菱形 (前方有人行横道)\n"
"int8 kInvertedTriangle = 6        # 倒三角 (减速让行)\n"
"int8 kOppositemarks = 7           # 对向标识\n"
"int8 kStopLane = 8                # 停止线\n"
"int8 kZebraCrossing = 9           # 斑马线\n"
"int8 kNoParkingArea = 10          # 禁止停车\n"
"int8 kGoreArea = 11               # 分道角区\n"
"int8 kGroundWords = 12            # 地面文字\n"
"int8 kDecelerationLine = 13       # 减速标识\n"
"int8 kSpeedBump = 14              # 减速带\n"
"int8 kManholeCover = 15           # 井盖\n"
"int8 kPole = 16    			      # 路灯杆\n"
"int8 kTypeNums = 17               # 总类型数\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::RoadmarkType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadmarkType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::RoadmarkType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::RoadmarkType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::mviz_apa_show::RoadmarkTypeEnum_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_ROADMARKTYPE_H
