// Generated by gencpp from file mviz_apa_show/RoadEdge.msg
// DO NOT EDIT!


#ifndef MVIZ_APA_SHOW_MESSAGE_ROADEDGE_H
#define MVIZ_APA_SHOW_MESSAGE_ROADEDGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mviz_apa_show/CurveCoeff.h>
#include <mviz_apa_show/CurveCoeff.h>
#include <mviz_apa_show/Point3DList.h>
#include <mviz_apa_show/Point2fList.h>
#include <mviz_apa_show/Point2fList.h>
#include <mviz_apa_show/Point3DList.h>
#include <mviz_apa_show/LineState.h>

namespace mviz_apa_show
{
template <class ContainerAllocator>
struct RoadEdge_
{
  typedef RoadEdge_<ContainerAllocator> Type;

  RoadEdge_()
    : id(0)
    , age(0)
    , curve_vehicle_coord()
    , curve_image_coord()
    , points_vehicle_coord()
    , points_image_coord()
    , fit_points_image_coord()
    , fit_points_vehicle_coord()
    , state()
    , side(0)
    , confidence(0.0)
    , camera_id()  {
    }
  RoadEdge_(const ContainerAllocator& _alloc)
    : id(0)
    , age(0)
    , curve_vehicle_coord(_alloc)
    , curve_image_coord(_alloc)
    , points_vehicle_coord(_alloc)
    , points_image_coord(_alloc)
    , fit_points_image_coord(_alloc)
    , fit_points_vehicle_coord(_alloc)
    , state(_alloc)
    , side(0)
    , confidence(0.0)
    , camera_id(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef uint32_t _age_type;
  _age_type age;

   typedef  ::mviz_apa_show::CurveCoeff_<ContainerAllocator>  _curve_vehicle_coord_type;
  _curve_vehicle_coord_type curve_vehicle_coord;

   typedef  ::mviz_apa_show::CurveCoeff_<ContainerAllocator>  _curve_image_coord_type;
  _curve_image_coord_type curve_image_coord;

   typedef  ::mviz_apa_show::Point3DList_<ContainerAllocator>  _points_vehicle_coord_type;
  _points_vehicle_coord_type points_vehicle_coord;

   typedef  ::mviz_apa_show::Point2fList_<ContainerAllocator>  _points_image_coord_type;
  _points_image_coord_type points_image_coord;

   typedef  ::mviz_apa_show::Point2fList_<ContainerAllocator>  _fit_points_image_coord_type;
  _fit_points_image_coord_type fit_points_image_coord;

   typedef  ::mviz_apa_show::Point3DList_<ContainerAllocator>  _fit_points_vehicle_coord_type;
  _fit_points_vehicle_coord_type fit_points_vehicle_coord;

   typedef  ::mviz_apa_show::LineState_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef int32_t _side_type;
  _side_type side;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _camera_id_type;
  _camera_id_type camera_id;





  typedef boost::shared_ptr< ::mviz_apa_show::RoadEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mviz_apa_show::RoadEdge_<ContainerAllocator> const> ConstPtr;

}; // struct RoadEdge_

typedef ::mviz_apa_show::RoadEdge_<std::allocator<void> > RoadEdge;

typedef boost::shared_ptr< ::mviz_apa_show::RoadEdge > RoadEdgePtr;
typedef boost::shared_ptr< ::mviz_apa_show::RoadEdge const> RoadEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mviz_apa_show::RoadEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mviz_apa_show::RoadEdge_<ContainerAllocator1> & lhs, const ::mviz_apa_show::RoadEdge_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.age == rhs.age &&
    lhs.curve_vehicle_coord == rhs.curve_vehicle_coord &&
    lhs.curve_image_coord == rhs.curve_image_coord &&
    lhs.points_vehicle_coord == rhs.points_vehicle_coord &&
    lhs.points_image_coord == rhs.points_image_coord &&
    lhs.fit_points_image_coord == rhs.fit_points_image_coord &&
    lhs.fit_points_vehicle_coord == rhs.fit_points_vehicle_coord &&
    lhs.state == rhs.state &&
    lhs.side == rhs.side &&
    lhs.confidence == rhs.confidence &&
    lhs.camera_id == rhs.camera_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mviz_apa_show::RoadEdge_<ContainerAllocator1> & lhs, const ::mviz_apa_show::RoadEdge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mviz_apa_show

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mviz_apa_show::RoadEdge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mviz_apa_show::RoadEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mviz_apa_show::RoadEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af56eda14a1054841e65193768c0d464";
  }

  static const char* value(const ::mviz_apa_show::RoadEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf56eda14a105484ULL;
  static const uint64_t static_value2 = 0x1e65193768c0d464ULL;
};

template<class ContainerAllocator>
struct DataType< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mviz_apa_show/RoadEdge";
  }

  static const char* value(const ::mviz_apa_show::RoadEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id                                                    # id 类型:uint32 字节数:4 取值范围:(0~2^32)\n"
"uint32 age				                                      # 检测帧数 类型:uint32 字节数:4 取值范围:(0~2^32)\n"
"CurveCoeff curve_vehicle_coord                               # 车身坐标系下曲线方程 字节数:40\n"
"CurveCoeff curve_image_coord                                 # 图像坐标系下的曲线方程 字节数:40\n"
"Point3DList points_vehicle_coord           # 车身坐标系下的采样点 字节数:24*n 取值范围(100>=x>=0, 20>=y>=-20) 最大容量:60\n"
"Point2fList points_image_coord             # 图像坐标系下的采样点 字节数:16*n 取值范围(w>=x>=0, h>=y>=0) 最大容量:60\n"
"Point2fList fit_points_image_coord         # 图像坐标系下的点集 (拟合抽样) 字节数:16*n 取值范围(w>=x>=0, h>=y>=0) 最大容量:60\n"
"Point3DList fit_points_vehicle_coord       # 车身坐标系下的点集 (拟合抽样) 字节数:24*n 取值范围(100>=x>=0, 20>=y>=-20) 最大容量:60\n"
"LineState state                                              # 线状态 类型:int 字节数:4 取值范围:(0~2)\n"
"int32 side                                                  # 路沿在左侧还是右侧 类型:int32 字节数:4 取值范围(0~1)\n"
"float32 confidence                                            # 置信度 类型:float 字节数:4 取值范围:(0~1)\n"
"uint32[] camera_id                         # 摄像头id \n"
"================================================================================\n"
"MSG: mviz_apa_show/CurveCoeff\n"
"# 曲线方程: y = c0 + c1*x + c2*x^2 + c3*x^3\n"
"float32 longitude_min  # view range start 类型:float 字节数:4 取值范围:(FLT_MIN~FLT_MAX)\n"
"float32 longitude_max  # view range end   类型:float 字节数:4 取值范围:(FLT_MIN~FLT_MAX)\n"
"float64 c0            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 c1            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 c2            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 c3            # 类型:float64 字节数:8 取值范围:(DOUBLE_MIN~DOUBLE_MAX)\n"
"float64 dev_c0        # c0的标准差，即，车道线横向位置的标准差\n"
"float64 dev_c1		  # c1的标准差，即，车道线航向角的标准差\n"
"float64 dev_c2        # c2的标准差，即，车道线原点处曲率的标准差\n"
"float64 dev_c3       # c3的标准差，即，车道线原点处曲率变化率的标注差\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point3DList\n"
"geometry_msgs/Point[] points \n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point2fList\n"
"Point2f[] points\n"
"================================================================================\n"
"MSG: mviz_apa_show/Point2f\n"
"float32 x\n"
"float32 y\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineState\n"
"LineStateEnum type\n"
"================================================================================\n"
"MSG: mviz_apa_show/LineStateEnum\n"
"int8 kDetected = 0      # 检测线\n"
"int8 kPredicted = 1     # 预测线\n"
"int8 kStableTrack = 2   # 稳定跟踪\n"
"int8 value\n"
;
  }

  static const char* value(const ::mviz_apa_show::RoadEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.age);
      stream.next(m.curve_vehicle_coord);
      stream.next(m.curve_image_coord);
      stream.next(m.points_vehicle_coord);
      stream.next(m.points_image_coord);
      stream.next(m.fit_points_image_coord);
      stream.next(m.fit_points_vehicle_coord);
      stream.next(m.state);
      stream.next(m.side);
      stream.next(m.confidence);
      stream.next(m.camera_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mviz_apa_show::RoadEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mviz_apa_show::RoadEdge_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "age: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.age);
    s << indent << "curve_vehicle_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::CurveCoeff_<ContainerAllocator> >::stream(s, indent + "  ", v.curve_vehicle_coord);
    s << indent << "curve_image_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::CurveCoeff_<ContainerAllocator> >::stream(s, indent + "  ", v.curve_image_coord);
    s << indent << "points_vehicle_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point3DList_<ContainerAllocator> >::stream(s, indent + "  ", v.points_vehicle_coord);
    s << indent << "points_image_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point2fList_<ContainerAllocator> >::stream(s, indent + "  ", v.points_image_coord);
    s << indent << "fit_points_image_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point2fList_<ContainerAllocator> >::stream(s, indent + "  ", v.fit_points_image_coord);
    s << indent << "fit_points_vehicle_coord: ";
    s << std::endl;
    Printer< ::mviz_apa_show::Point3DList_<ContainerAllocator> >::stream(s, indent + "  ", v.fit_points_vehicle_coord);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::mviz_apa_show::LineState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "side: ";
    Printer<int32_t>::stream(s, indent + "  ", v.side);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "camera_id[]" << std::endl;
    for (size_t i = 0; i < v.camera_id.size(); ++i)
    {
      s << indent << "  camera_id[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.camera_id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVIZ_APA_SHOW_MESSAGE_ROADEDGE_H
